# Generated by Django 5.2.2 on 2025-06-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='seat_type',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver')], max_length=10),
        ),
    ]
